### ISSUE TITLE
Multiple steam-tradeoffers instances

### ISSUE THREAD

**Issue by dolanmiu** [steam-forward/node-steam-forum#14]
Whenever I have more than one steam-tradeoffers instance, I get this error:
```
C:\Users\dolan.ADSM\Documents\GitHub\cs-go-mini-games\website\node_modules\steam-tradeoffers\index.js:94
        throw accessError;
              ^
Error: Access Denied
    at SteamTradeOffers.<anonymous> (C:\Users\dolan.ADSM\Documents\GitHub\cs-go-mini-games\website\node_modules\steam-tradeoffers\index.js:90:25)
    at Request.self.callback (C:\Users\dolan.ADSM\Documents\GitHub\cs-go-mini-games\website\node_modules\request\request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\dolan.ADSM\Documents\GitHub\cs-go-mini-games\website\node_modules\request\request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\dolan.ADSM\Documents\GitHub\cs-go-mini-games\website\node_modules\request\request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Any ideas?

**Comment by dolanmiu** [comment]
No one ever considered the possibility of using multiple steam-tradeoffer instances?

**Comment by scholtzm** [comment]
When do you get that error?

Also the stack trace is now useless since the library has changed in 2.0.0.
