### ISSUE TITLE
Array from items_to_recieve from CEcon_TradeOffer?

### ISSUE THREAD

**Issue by iJamesPHP** [steam-forward/node-steam-forum#173]
I'm currently trying to get the Asset ID of each item I'm receiving in a trade offer.

Here's my current code: 

```
body.response.trade_offers_received.forEach(function(offer) {
      // Check if they are a robber
           if (offer.trade_offer_state != 2 || offer.items_to_give) {
             jamesBug('They tried to rob the bot, declining.');
             Bot.offers.declineOffer({'tradeOfferId': offer.tradeofferid});
             return;
           }
        if (offer.trade_offer_state === 2) {
        
        jamesBug('msg: '+offer.message);
      	jamesBug('i2r: '+offer.items_to_receive.length);
        jamesBug('id of first item: '+offer.items_to_receive[0].assetid)

```
This is what I get logged out:

```

[Sun, 28 Feb 2016 10:24:44 GMT] msg: 5699433 | This is an automatic trade generated by OPSkins. Security token: GdYpnl
[Sun, 28 Feb 2016 10:24:44 GMT] i2r: 1
/Users/James/Sites/SteamNode/run.js:77
        jamesBug('id: '+offer.items_to_receive[0].assetid)
                          ^

TypeError: Cannot read property '0' of undefined
    at /Users/James/Sites/SteamNode/run.js:77:27
    at Array.forEach (native)
    at /Users/James/Sites/SteamNode/run.js:65:43
    at Object.doAPICall.bind.callback (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/index.js:163:7)
    at SteamTradeOffers.<anonymous> (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/index.js:491:15)
    at Request.self.callback (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/James/Sites/SteamNode/node_modules/steam-tradeoffers/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)

```

Maybe I am incorrectly handling the array, if it even is an array?

Thanks for the help,

James

**Comment by andrewda** [comment]
Have you tried simply printing out the offer.items_to_receive? You might want to try that as it's step 1 of debugging.
