### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by TriggerJiggers** [steam-forward/node-steam-forum#251]
So here is the error.

TypeError: Cannot read property 'value' of undefined
    at Query._callback (C:\Users\Logan\Desktop\csgolottery\bot\sell.js:575:23)
    at Query.Sequence.end (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

This error occurs when someone tries to deposit items.

Here is some of the code for the bot, I left the part out with the username password, api key, etc. But the bot logs in correctly so that shouldn't matter,

CODE: http://pastebin.com/KTa4g9jE

**Comment by jwigley** [comment]
What line number in pastebin is line 575 from sell.js?

**Comment by TriggerJiggers** [comment]
maxbet=row[0].value;

**Comment by jwigley** [comment]
```js
var maxbet=0;
mysqlConnection.query('SELECT `value` FROM `info` WHERE `name`=\'maxbet\'', function(err, row, fields) {
    maxbet=row[0].value;
    ...
```
So you're trying to get something from your database, but you are getting 0 rows returned. You're not checking how many rows were returned and just assuming you have something in row[0].

**Comment by TriggerJiggers** [comment]
So I have switched the site to the correct database, and this is the error I am getting. It was TypeError: Cannot read property '0' of undefined

Instead of 'value'

TypeError: Cannot read property '0' of undefined
    at Query._callback (C:\Users\Logan\Desktop\csgolottery\bot\sell.js:490:46)
    at Query.Sequence.end (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Protocol._validateEnqueue (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\Protocol.js:218:6)
    at Protocol._enqueue (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\protocol\Protocol.js:129:13)
    at Connection.query (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\mysql\lib\Connection.js:201:25)
    at C:\Users\Logan\Desktop\csgolottery\bot\sell.js:489:23
    at Array.forEach (native)
    at C:\Users\Logan\Desktop\csgolottery\bot\sell.js:481:41
    at Object.doAPICall.bind.callback (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\steam-tradeoffers\index.js:149:7)
    at SteamTradeOffers.<anonymous> (C:\Users\Logan\Desktop\csgolottery\bot\node_modules\steam-tradeoffers\index.js:464:15)

							if(offer.items_to_receive.length > row[0].value) {



Here is line 490:

**Comment by jwigley** [comment]
Add some debugging.
```js
console.log( row );
```
Is row defined? 

It looks to be a similiar error to your first one. You are blindly assuming row is populated without first checking how many rows were returned.
