### ISSUE TITLE
Steam Bot Error. Error: Logon fail: 85

### ISSUE THREAD

**Issue by whoami248** [steam-forward/node-steam-forum#280]
root@Jackpot:/var/Bot# nodejs tradebot.js
socket timed out
socket closed
connecting to 146.66.152.12:27018
socket timed out
socket closed
connecting to 72.165.61.187:27017
connected
encrypt request
handshake complete
logon fail: 85, sessionID: 8983499
events.js:85
      throw er; // Unhandled 'error' event
      ^

Error: Logon fail: 85
    at SteamClient.handlers.(anonymous function) (/var/www/Bot/node_modules/stea                     m/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/var/www/Bot/node_modules/steam/lib/steam_cl                     ient.js:106:26)
    at SteamClient.handlers.(anonymous function) (/var/www/Bot/node_modules/stea                     m/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/var/www/Bot/node_modules/steam/lib/steam_cl                     ient.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/var/www/Bot/node_modules/steam/lib/connection.js                     :50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
root@Jackpot:/var/www/Bot#

`   **Please help**

**Comment by gokarter24** [comment]
Are you using proxies?

**Comment by zkimi** [comment]
Same error plz help me :

connecting to 72.165.61.185:27017
connected
2%   encrypt request
handshake complete
logon fail: 85, sessionID: 3104021
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Logon fail: 85
    at SteamClient.handlers.(anonymous function) (/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/bot/node_modules/steam/lib/steam_client.js:106:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/bot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)

**Comment by DixieF** [comment]
Provide the 2fa auth code.
