### ISSUE TITLE
Steam Bot Error. Error: Logon fail: 85

### ISSUE THREAD

**Issue by dmitriy28** [steam-forward/node-steam-forum#289]
Hello, please help me
How I can fix it?
Error: Logon fail: 85
    at SteamClient.handlers.(anonymous function) (/bot/node_modules/steam/lib/handlers/user.js:178:11)
    at SteamClient._netMsgReceived (/bot/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/bot/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/bot/node_modules/steam/lib/steam_client.js:106:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Connection._readPacket (/bot/node_modules/steam/lib/connection.js:50:8)
    at emitNone (events.js:105:13)
    at Connection.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:500:10)
Thanks)

**Comment by andrewda** [comment]
You need to provide a 2FA code.

**Comment by dmitriy28** [comment]
I did, but still the same error

**Comment by andrewda** [comment]
Show your code

**Comment by dmitriy28** [comment]
[bot.zip](https://github.com/steam-forward/node-steam-forum/files/1050558/bot.zip)
I cut node modules

**Comment by andrewda** [comment]
You need to use `node-steam-totp` to generate auth codes.

**Comment by dmitriy28** [comment]
only node-steam totp?
Must I install:
npm install steam
npm install steamcommunity
npm i steamcommunity-mobile-confirmations 
?

**Comment by andrewda** [comment]
You just need `node-steam-totp` to generate auth codes. Read the documentation: https://github.com/DoctorMcKay/node-steam-totp

Also, the code you uploaded contains your username and password. You should take that code down and change your password immediately.

**Comment by dmitriy28** [comment]
okey thank you)

**Comment by dmitriy28** [comment]
Sorry,how can I install node-steam-totp?
If you can give me please instructions))

**Comment by andrewda** [comment]
`npm install steam-totp`

Then, in your code:

```javascript
var SteamTotp = require('steam-totp');
var authCode = SteamTotp.generateAuthCode('your shared secret');
```

**Comment by dmitriy28** [comment]
code I must write in steambot.js?

**Comment by andrewda** [comment]
Put that code wherever you're logging into Steam as the `authCode`.

**Comment by dmitriy28** [comment]
okey,thank you very much)

**Comment by dmitriy28** [comment]
Sorry,my bot does not send the winnings
