### ISSUE TITLE
error in makeoffer()

### ISSUE THREAD

**Issue by Govind13100** [steam-forward/node-steam-forum#297]
@Alex7Kom @Efreak @scholtzm @dragonbanshee @andrewda  Why this is asking to trade after 15 days ???

I am doing this on my old device still it ask to wait for 15 days????

```
C:\Users\User\Desktop\govind\node-steam-tradeoffers-master\examples\offerbot.js:71
          throw err;
          ^

Error: There was an error sending your trade offer.  Please try again later. (15)
    at SteamTradeOffers.<anonymous> (C:\Users\User\Desktop\govind\node-steam-tradeoffers-master\index.js:315:17)
    at Request.self.callback (C:\Users\User\Desktop\govind\node-steam-tradeoffers-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\User\Desktop\govind\node-steam-tradeoffers-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\User\Desktop\govind\node-steam-tradeoffers-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
```

Is there anyone to guide me on this?
Any help / suggestion would be very helpful for me!!
Thanks in advance!!!!

**Comment by scholtzm** [comment]
https://steamerrors.com/15

**Comment by Govind13100** [comment]
Thanks a lot!

**Comment by Govind13100** [comment]
Thanks for that ,

The reasons which are stated there are all full-field at my end. There is nothing to do with those reasons from my account.
How I know that :
Just before trading programmatically , I trade manually from official steam website and the result was positive.

But when i did that with same steamid using this bot, it show 15 error code.

if those are the reasons then how could i was able to trade through steam official website??

Anything on this??
would be very appreciable >>>

**Comment by dragonbanshee** [comment]
You probably aren't constructing your trade offer correctly. Please paste your trade offer code so we may see it.

Also you don't need to tag everyone when you post, everyone who is watching will get notified of every post. Here are the watchers: https://github.com/steam-forward/node-steam-forum/watchers

**Comment by Govind13100** [comment]
Here is my code please have a look

```
var fs = require('fs');
var crypto = require('crypto');

var Steam = require('steam');
var SteamWebLogOn = require('steam-weblogon');
var getSteamAPIKey = require('steam-web-api-key');
var SteamTradeOffers = require('../'); // change to 'steam-tradeoffers' if not running from the examples subdirectory

var admin = '76561197960912172'; // put your steamid here so the bot can send you trade offers

var logOnOptions = {
 account_name: '*********',
 password: '*******'
};

var authCode = ''; // code received by email

try {
 logOnOptions.sha_sentryfile = getSHA1(fs.readFileSync('sentry'));
} catch (e) {
 if (authCode !== '') {
   logOnOptions.auth_code = authCode;
 }
}

// if we've saved a server list, use it
if (fs.existsSync('servers')) {
 Steam.servers = JSON.parse(fs.readFileSync('servers'));
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
var offers = new SteamTradeOffers();

steamClient.connect();
steamClient.on('connected', function() {
 steamUser.logOn(logOnOptions);
});

function offerItems() {
 offers.loadMyInventory({
   appId: 730,
   contextId: 2
 }, function(err, items) {
   var item;
   // picking first tradable item
   for (var i = 4; i < items.length; i++) {
     if (items[i].tradable) {
       item = items[i];
       break;
     }
   } console.log(item.id);
   // if there is such an item, making an offer with it
   if (item) {
     offers.makeOffer ({
       partnerSteamId: admin,
       itemsFromMe: [
         {
           appid: 730,
           contextid: 2,
           amount: 1,
           assetid: item.id
         }
       ],
       itemsFromThem: [],
       message: 'This is test'
     }, function(err, response) {
       if (err) {
         throw err;
       }
       console.log(response);
     });
   }
 });
}

steamClient.on('logOnResponse', function(logonResp) {
 if (logonResp.eresult === Steam.EResult.OK) {
   console.log('Logged in!');
   steamFriends.setPersonaState(Steam.EPersonaState.Online);

   steamWebLogOn.webLogOn(function(sessionID, newCookie) {
     getSteamAPIKey({
       sessionID: sessionID,
       webCookie: newCookie
     }, function(err, APIKey) {
       offers.setup({
```

**Comment by dragonbanshee** [comment]
Try to make the numbers in itemsFromMe strings instead of numbers. I think this has worked for me in the past.

```javascript
itemsFromMe: [
{
    "appid": "730",
    "contextid": "2",
    "amount": "1",
    "assetid": "" + item.id
}
]

**Comment by Govind13100** [comment]
hie, 
Thanks for you reply ,
Nothings change, the same error (15) code is coming. 
Any other suggestions please ??
