### ISSUE TITLE
steam-tradeoffers: Cannot read property 'post' of undefined

### ISSUE THREAD

**Issue by steeveenson** [steam-forward/node-steam-forum#305]
##### Checklist:
- [x] I have tried the search and there is no similar issues or a similar issue doesn't appear to be solved

##### Problem description:
I'm trying to send a tradeoffer with my bot. 
It throws the following error:

`TypeError: Cannot read property 'post' of undefined
    at SteamTradeOffers.makeOffer (/root/nodejs/node_modules/steam-tradeoffers/index.js:303:25)
    at requestItems (/root/nodejs/nodebot.js:245:13)
    at Query._callback (/root/nodejs/nodebot.js:98:21)
    at Query.Sequence.end (/root/nodejs/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/root/nodejs/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/root/nodejs/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/root/nodejs/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/nodejs/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/nodejs/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/nodejs/node_modules/mysql/lib/Connection.js:103:28)
`

##### I have already tried:

- [x] Searching on through Google, but couldn't find anything like that which is related to Steam.
- [x] Debugging my code to see if I'm not passing a variable the right way which make this post-property undefined.
- [x] Trying to check the related part of (node_modules/steam-tradeoffers/index.js:303:25)

I'm completely lost.

##### My code:

```js
// The following function calls requestItems.
chooseBot(function(bot){
    requestItems(bot, data[0], token, msg, data[1]);
});
//function requestItems()
function requestItems(bot, steamId, token, message, items){
    console.log("[requestItems] - Using bot: Bot #"+bot.options.botId);
	console.log("[requestItems] - Requested deposit for: "+steamId);
	console.log("[requestItems] - Token: "+token);
	console.log("[requestItems] - Msg: "+message);
	console.log("[requestItems] - Requested items: "+items); 
	bot.offers.makeOffer({
		partnerSteamId: steamId,
		accessToken: token,
		message: message,
		itemsFromThem: items
	}, function(err, response) {
      if(err){
        console.log("[requestItems] - There was an error while requesting the items.");
		socket.emit('notifyUser', steamId);
      }else{
		console.log("[requestItems] - Tradeoffer successfully sent.");
		console.log("[requestItems] - Response: "+response);
	  }
	});
}
```

##### I use the following libraries:
dragonbanshee/node-steam-parentbot (A lots of other libraries included in this one)
Alex7Kom/node-steam-tradeoffers (The problem occurs while using this)

**Comment by alex7kom** [comment]
Make sure `.setup()` is called before any other tradeoffers method.
