### ISSUE TITLE
Nothing happens after login

### ISSUE THREAD

**Issue by Someone9** [steam-forward/node-steam-forum#58]
After the bot has logged in nothing happens. The only thing that is printed to the console is "Logged In!" and nothing more but the program doesn't exit, it keeps running but isn't doing anything after the login. No tradeoffer even though I have specified the steamID in the code. Pls halp D:

**Comment by andrewda** [comment]
There's absolutely no way we can help you unless you post your code...

**Comment by Someone9** [comment]
The code is just the offerbot from the samples

**Comment by jwigley** [comment]
The offerbot.js example offers items with [appId: 440, contextId: 2]. Do you have items of that type? If not, it won't offer a trade.

Add some debugging into the offerItems method to find out what's happening.

**Comment by andrewda** [comment]
If you're not using an old sentry file, you'll also need to be logged into your bot's account for at least a week.

**Comment by Someone9** [comment]
Ok so I have done some debugging into the offerItems and I know that I have items of the type of the appid and contextid, but now after the bot has logged on i get this error: 
Error: 400
    at SteamTradeOffers.<anonymous> (C:\Users\Axel\steambot\node_modules\steam-tradeoffers\index.js:369:18)
    at Request.self.callback (C:\Users\Axel\steambot\node_modules\steam-tradeoffers\node_modules\request\request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Axel\steambot\node_modules\steam-tradeoffers\node_modules\request\request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Axel\steambot\node_modules\steam-tradeoffers\node_modules\request\request.js:1003:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
