### ISSUE TITLE
this._connection.send

### ISSUE THREAD

**Issue by overheader** [steam-forward/node-steam-forum#61]
Hello
There was an error:

/main/node_modules/steam/lib/steam_client.js:124
  this._connection.send(Buffer.concat([header.toBuffer(), body]));
                  ^
TypeError: Cannot read property 'send' of undefined
    at SteamClient._send /main/node_modules/steam/lib/steam_client.js:124:19)
    at SteamClient.send (/main/node_modules/steam/lib/steam_client.js:133:8)
    at SteamUser.requestWebAPIAuthenticateUserNonce (/main/node_modules/steam/lib/handlers/user/index.js:37:16)
    at SteamWebLogOn.<anonymous> (/main/node_modules/steam-weblogon/index.js:29:23)
    at ClientRequest.<anonymous> (/main/node_modules/steam-weblogon/node_modules/steam-web-api/index.js:34:9)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)

It happened the first time. Is it possible to ignore the error the next time, or fix it?

**Comment by dragonbanshee** [comment]
This is happening because you are trying to do something on the steam network without being connected. Posting some code on pastebin would be helpful.
