### ISSUE TITLE
Illegal offset: 0 <= 1 (+1) <= 1

### ISSUE THREAD

**Issue by overheader** [steam-forward/node-steam-forum#70]
Hello

This error occurs when reconnecting to Steam
There was an error:

/home/server/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3007
                        throw(e);
                              ^
RangeError: Illegal offset: 0 <= 1 (+1) <= 1
    at RangeError (native)
    at module.exports.ByteBufferPrototype.readVarint32 (/home/server/node_modules/steam/node_modules/bytebuffer/dist/ByteBufferNB.js:1469:80)
    at ProtoBuf.Reflect.MessagePrototype.decode (/home/server/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3281:36)
    at Function.Message.decode (/home/server/node_modules/steam/node_modules/protobufjs/dist/ProtoBuf.js:3002:37)
    at Object.<anonymous> (/home/server/node_modules/steam/lib/handlers/user/index.js:41:77)
    at SteamClient._netMsgReceived (/home/server/node_modules/steam/lib/steam_client.js:180:28)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/server/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)

**Comment by scholtzm** [comment]
You should post this to `node-steam` issue tracker with minimal test case if you believe this is an actual bug.

**Comment by overheader** [comment]
I have an account there is a change at this time on the other, it can somehow affect? It is possible that at the time of the change could be carried out any action with Steam.
